config/routes.rb
NyTechPodcast::Application.routes.draw do

  resources :episodes

  root 'pages#home'

  get 'gallery' => 'pages#gallery'
  get 'aboutus' => 'pages#aboutus'
  get 'episode' => 'pages#episode'

end

app/models/episode.rb
class Episode < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	before_action :real_episodes

	def real_episodes
		@real_eps = Episode.all.where(:display => true).order("created_at DESC")
		@short_list = Episode.all.where(:display => true).order("created_at DESC").first
	end

end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]

  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
        format.json { render action: 'show', status: :created, location: @episode }
      else
        format.html { render action: 'new' }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to episodes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:name, :episode_number, :guest, :embed_link, :picture, :display, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

  def gallery
  end

  def aboutus
  end

  def episode
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_form.html.erb
<%= form_for(@episode) do |f| %>
  <% if @episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% @episode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :episode_number %><br>
    <%= f.number_field :episode_number, autofocus: true, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :guest %><br>
    <%= f.text_field :guest, autofocus: true, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :embed_link %><br>
    <%= f.text_field :embed_link, autofocus: true, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :picture %><br>
    <%= f.text_field :picture, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, autofocus: true, class: "form-control" %> 
  </div>

  <div class="form-group">
    <%= f.label :display %><br>
    <%= f.check_box :display, autofocus: true, class: "form-control" %> <!-- Try to make the checkbox bigger -->
  </div>

  <div class="actions">
    <%= f.submit class: 'btn br-lblue'%>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing episode</h1>

<%= render 'form' %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<h1>Listing episodes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Episode number</th>
      <th>Guest</th>
      <th>Embed link</th>
      <th>Picture</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= episode.name %></td>
        <td><%= episode.episode_number %></td>
        <td><%= episode.guest %></td>
        <td><%= episode.embed_link %></td>
        <td><%= episode.picture %></td>
        <td><%= link_to 'Show', episode %></td>
        <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
        <td><%= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/new.html.erb
<div class="container">
	<h1>New episode</h1>

	<%= render 'form' %>

	<%= link_to 'Back', episodes_path %>
</div>

app/views/episodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @episode.name %>
</p>

<p>
  <strong>Episode number:</strong>
  <%= @episode.episode_number %>
</p>

<p>
  <strong>Guest:</strong>
  <%= @episode.guest %>
</p>

<p>
  <strong>Embed link:</strong>
  <%= @episode.embed_link %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @episode.picture %>
</p>

<%= link_to 'Edit', edit_episode_path(@episode) %> |
<%= link_to 'Back', episodes_path %>

app/views/layouts/_footer.html.erb
<!-- Footer Start -->

<div class="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-3 col-sm-6">
				<!-- Footer Widget -->
				<div class="footer-widget">
					<!-- Logo Icon -->
					<!-- Heading -->
					<h2><a href="index.html"> NY Tech Podcast</a></h2>
					<!-- Paragraph -->
					<p><a id="contact">Weekly episodes talking to founders and developers about their businesses and ideas. </a></p>
					<!-- Social Media -->
					<div class="social"><!-- 
						<a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
						<a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a> -->
						<a href="https://twitter.com/nytechpodcast" class="twitter"><i class="fa fa-twitter"></i></a>
						<a href="#" class="pinterest"><i class="fa fa-pinterest"></i></a> 
						<a href="https://www.linkedin.com/pub/mike-sabat/3/870/643" class="linkedin"><i class="fa fa-linkedin"></i></a>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-6">
				<!-- Footer Widget -->
				<div class="footer-widget">
					<!-- Heading -->
					<h5><i class="fa fa-plus br-red"></i> Navigation Menu</h5>
					<div class="row">
						<div class="col-md-6 col-sm-6 col-xs-6">
							<!-- Menu Icons link -->
							<ul class="list-unstyled">
								<li><a href="#"><i class="fa fa-home br-red"></i> Home</a></li>
								<li><a href="#"><i class="fa fa-book br-yellow"></i> All Episodes</a></li>
								<!-- <li><a href="#contact"><i class="fa fa-phone br-green"></i> Contact Us</a></li>
								<li><a href="#"><i class="fa fa-gear br-lblue"></i> Service</a></li>
								<li><a href="#"><i class="fa fa-comment br-purple"></i> Testimonial</a></li> -->
							</ul>
						</div>
						<div class="col-md-6 col-sm-6 col-xs-6">
							<!-- Menu Icons link -->
							<ul class="list-unstyled">
								<!-- <li><a href="#"><i class="fa fa-check br-green"></i> Features</a></li> -->
								<li><a href="#"><i class="fa fa-search br-pink"></i> Most Recent</a></li>
								<li><a href="#"><i class="fa fa-user br-orange"></i> About </a></li>
								<!-- <li><a href="#"><i class="fa fa-sign-in br-red"></i> Register</a></li>
								<li><a href="#"><i class="fa fa-file br-blue"></i> Recent News</a></li> -->
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div class="clearfix visible-sm"></div>
			<div class="col-md-3 col-sm-6">
				<!-- Footer Widget -->
				<div class="footer-widget">
					<!-- Heading -->
					<h5><i class="fa fa-map-marker br-yellow"></i> Contact Us</h5>
					<address>
						<i class="fa fa-home br-green"></i> 88th Street and E End Ave,  <br>
						&nbsp; &nbsp; &nbsp; &nbsp; New York, NY 10028  <br>
						<!-- &nbsp; &nbsp; &nbsp; &nbsp; Bangalore - 234543 <br> -->
						<!-- <span><i class="fa fa-phone br-orange"></i> +91 123-456-2345</span> -->
						<span><i class="fa fa-envelope-o br-blue"></i> <a href="#">abc@example.com</a></span>
					</address>
				</div>
			</div>
			<!-- <div class="col-md-3 col-sm-6"> -->
				<!-- Footer Widget -->
				<!-- <div class="footer-widget"> -->
					<!-- Heading -->
					<!-- <h5><i class="fa fa-location-arrow br-lblue"></i> Location</h5> -->
					<!-- Google Map -->
					<!-- <div class="map"> -->
						<!-- Image -->
						<!-- <img src="/assets/map.png" class="img-responsive" alt=""> -->
						<!-- Map Marker -->
						<!-- <i class="fa fa-map-marker marker india lblue"></i>
						<i class="fa fa-map-marker marker usa orange"></i>
						<i class="fa fa-map-marker marker africa green"></i>
					</div>
					<span class="location-name">
						<i class="fa fa-map-marker br-lblue"></i> India &nbsp;&nbsp;
						<i class="fa fa-map-marker br-orange"></i> USA &nbsp;&nbsp;
						<i class="fa fa-map-marker br-green"></i> Africa
					</span>
				</div>
			</div>
		</div> -->
		<!-- Footer Copyright -->
		<div class="footer-copyright">
			<p>© Copyright 2014 <a href="#">NY Tech Podcast</a></p>
		</div>
	</div>
</div>

<!-- Footer End -->

<!-- Footer End -->

<!-- Scroll to top -->
<span class="totop" style="display: none;"><a href="#"><i class="fa fa-angle-up"></i></a></span>
<script type="text/javascript">

// SLIDER REVOLUTION Java Script
	jQuery(document).ready(function() {
		   jQuery('.tp-banner').revolution(
			{
				delay:9000,
				startheight:500,
				
				hideThumbs:10,
				
				navigationType:"none",	
				
				
				hideArrowsOnMobile:"on",
				
				touchenabled:"on",
				onHoverStop:"on",
				
				navOffsetHorizontal:0,
				navOffsetVertical:20,
				
				stopAtSlide:-1,
				stopAfterLoops:-1,

				shadow:0,
				
				fullWidth:"on",
				fullScreen:"off"
			});
	});

// Cycle Slide Js 

	$('#box-slider-one').cycle({ 
		fx:    'uncover',  
		speed:    200, 
		timeout:  2500 
	});

/* ******************************************** */
/* plot js */
/* *************************************** */  
		
	$(function() {
		/* Chart data #1 */
		var d1 = [[0, 0], [1, 1.5], [2, 3.2], [3, 4.1],[4, 5.1], [5, 5], [6, 5.3], [7, 6],[8, 6.3], [9, 7], [10, 7.5], [11, 8]];

		var options = {
			series: {
			  lines: {
				 show: true, fill: false, lineWidth:1
			  },
			  points: {
				 show: true, fill: true, lineWidth:2, radius:3, fillColor: "#fff"
			  },
			  shadowSize: 0
		   },
			colors :["#fff"],
		   grid: {
			  hoverable: true, color: "#fff", backgroundColor:null ,borderWidth:0, borderColor:"#fff", labelMargin:10
		   },
		   xaxis: {
			  ticks: 10,
			  font: {
					size: 12,
					color: ["#fff"]
				}
		   },
		   yaxis: {
			  ticks: 5,
			  font: {
					size: 12,
					color: ["#fff"]
				}
		   }, 
		   legend: {
			  backgroundOpacity:0,
			  noColumns:2,
			  labelBoxBorderColor: null
		   }
		};
		
		$("<div id='tooltip'></div>").css({
			position: "absolute",
			display: "none",
			"border-radius":"1px",
			padding: "4px 5px",
			color:"#999",
			"font-size":"11px",
			"background-color": "#fff",
			"border":"1px solid #ccc",
			"z-index": "20"
		}).appendTo("body");

		$(".plot-chart").bind("plothover", function (event, pos, item) {
				if (item) {
					var x = item.datapoint[0].toFixed(2),
						y = item.datapoint[1].toFixed(2);

					$("#tooltip").html(x + ", " + y)
						.css({top: item.pageY+5, left: item.pageX+5})
						.fadeIn(200);
				} else {
					$("#tooltip").hide();
				}
		});

		// $.plot(".plot-chart", [ {data: d1,  label: "Revenue"} ], options);
	});
	
// Type your codde here
</script>

<div id="tooltip" style="position: absolute; display: none; border-top-left-radius: 1px; border-top-right-radius: 1px; border-bottom-right-radius: 1px; border-bottom-left-radius: 1px; padding: 4px 5px; color: rgb(153, 153, 153); font-size: 11px; background-color: rgb(255, 255, 255); border: 1px solid rgb(204, 204, 204); z-index: 20;"></div><script id="hiddenlpsubmitdiv" style="display: none;"></script><script>try{for(var lastpass_iter=0; lastpass_iter < document.forms.length; lastpass_iter++){ var lastpass_f = document.forms[lastpass_iter]; if(typeof(lastpass_f.lpsubmitorig2)=="undefined"){ lastpass_f.lpsubmitorig2 = lastpass_f.submit; lastpass_f.submit = function(){ var form=this; var customEvent = document.createEvent("Event"); customEvent.initEvent("lpCustomEvent", true, true); var d = document.getElementById("hiddenlpsubmitdiv"); if (d) {for(var i = 0; i < document.forms.length; i++){ if(document.forms[i]==form){ d.innerText=i; } } d.dispatchEvent(customEvent); }form.lpsubmitorig2(); } } }}catch(e){}</script>

app/views/layouts/_header.html.erb
			<div class="header">
				<!-- Header Information -->
				<div class="header-info">
					<div class="container">
						<div class="row">
							<div class="col-md-4 col-sm-4">
								<!-- Social Media -->
								<div class="social">
									<!-- <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
									<a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a> -->
									<a href="https://twitter.com/nytechpodcast" class="twitter"><i class="fa fa-twitter"></i></a>
									<a href="#" class="pinterest"><i class="fa fa-pinterest"></i></a> 
									<a href="https://www.linkedin.com/pub/mike-sabat/3/870/643" class="linkedin"><i class="fa fa-linkedin"></i></a>
								</div>
							</div>
							<div class="col-md-4 col-sm-4">
								<!-- Search Box -->
								<!-- <div class="search">
									<form>
										<div class="input-group">
											<input type="text" class="form-control" placeholder="Text to search">
											<span class="input-group-btn">
												<button class="btn" type="button"><i class="fa fa-search"></i></button>
											</span>
										</div>
									</form>
								</div> -->
							</div>
							<div class="col-md-4 col-sm-4">
								<!-- Contact Info -->
								<!-- <div class="contact-info">
									<span><i class="fa fa-phone br-lblue"></i> <strong>+91 234 - 234 - 3231</strong></span>
								</div> -->
							</div>
						</div>
					</div>
				</div>
				<!-- Header Navigation -->
				<div class="header-navigation">
					<div class="container">
						<div class="row">
							<div class="col-md-4">
								<!-- Logo -->
								<div class="logo">
									<!-- Heading -->
									<h1><a href='/'> NY Tech Podcast</a></h1>
								</div>
							</div>
							<div class="col-md-8">
								<!-- Bootstrap Navbar -->
								<nav class="navbar navbar-default" role="navigation">
									<!-- Brand and toggle get grouped for better mobile display -->
									<div class="navbar-header">
										<button type="button" class="navbar-toggle br-orange" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
											<span class="sr-only">Toggle navigation</span>
											<span class="icon-bar"></span>
											<span class="icon-bar"></span>
											<span class="icon-bar"></span>
										</button>
									</div>
									<!-- Collect the nav links, forms, and other content for toggling -->
									<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
										<ul class="nav navbar-nav navbar-right">
											<li>
												<a href="/" class="br-orange">
													<!-- Link Icon -->
													<i class="fa fa-home link-icon"></i>
													<!-- Link Title -->
													<span class="link-title">Home</span>
												</a>
											</li>
											<li class="dropdown">
												<a href="#" class="br-purple dropdown-toggle" data-toggle="dropdown"> 
													<!-- class="dropdown-toggle br-purple" data-toggle="dropdown">
													Link Icon -->
													<i class="fa fa-file link-icon"></i>
													<!-- Link Title -->
													<span class="link-title">All Eps <b class="fa fa-angle-down"></b></span> 
												</a>
												<ul class="dropdown-menu dropdown-sm">
													<li>
														<div class="row">
															<div class="col-md-6">
																<div class="col-inner col-disable">
																	<h4 class="br-orange"><i class="fa fa-share heading-icon"></i> Past Episodes</h4>
																	<p>New episodes are posted weekly. Please subscribe on iTunes or your favorite podcasting platform.</p>
																</div>
															</div>
															<div class="col-md-6">
																<div class="col-inner">
																	<ul class="list-unstyled">
																		<li><a href="/gallery"><i class="fa fa-arrow-right dd-link-icon"></i> All Episodes - Gallery</a></li>
																		<li><a href="coming-soon.html"><i class="fa fa-arrow-right dd-link-icon"></i> Beta Episode</a></li>
																		<!-- <li><a href="http://nytechpodcast.podbean.com/2014/03/22/nytech-podcast-01/"><i class="fa fa-arrow-right dd-link-icon"></i> Features</a></li>
																		<li><a href="gallery.html"><i class="fa fa-arrow-right dd-link-icon"></i> Gallery</a></li>
																		<li><a href="login.html"><i class="fa fa-arrow-right dd-link-icon"></i> Login</a></li>
																		<li><a href="login.html"><i class="fa fa-arrow-right dd-link-icon"></i> Register</a></li> -->
																	</ul>
																</div>
															</div>
														</div>
													</li>
												</ul>
											</li>
											<li class="dropdown">
												<a href="#" class="dropdown-toggle br-pink" data-toggle="dropdown">
													<!-- Link Icon -->
													<i class="fa fa-file link-icon"></i>
													<!-- Link Title -->
													<span class="link-title">Subscribe <b class="fa fa-angle-down"></b></span> 
												</a>
												<ul class="dropdown-menu dropdown-default">
													<li><a href="https://itunes.apple.com/us/podcast/ny-tech-podcast/id846408334?mt=2"><i class="fa fa-arrow-right dd-link-icon lblue"></i> iTunes</a></li>
													<li><a href="http://www.stitcher.com/podcast/ny-tech-podcast"><i class="fa fa-arrow-right dd-link-icon lblue"></i> Stitcher</a></li>
													<li><a href="http://tunein.com/radio/NY-Tech-Podcast-p595467/"><i class="fa fa-arrow-right dd-link-icon lblue"></i> Tunein Radio</a></li>
													<li><a href="landing-page.html"><i class="fa fa-arrow-right dd-link-icon lblue"></i> Double Twist</a></li>
													<li><a href="http://pcasts.in/nytechpodcast"><i class="fa fa-arrow-right dd-link-icon lblue"></i> Pocket Cast</a></li>
													<!-- <li><a href="service.html"><i class="fa fa-arrow-right dd-link-icon lblue"></i> Service</a></li>
													<li><a href="sitemap.html"><i class="fa fa-arrow-right dd-link-icon lblue"></i> Site Map</a></li>
													<li><a href="time-line.html"><i class="fa fa-arrow-right dd-link-icon lblue"></i> Time Line</a></li> -->
												</ul>
											</li>
											<li class="dropdown">
												<a href="#" class="dropdown-toggle br-lblue" data-toggle="dropdown">
													<!-- Link Icon -->
													<i class="fa fa-file link-icon"></i>
													<!-- Link Title -->
													<span class="link-title">Newest <b class="fa fa-angle-down"></b></span> 
												</a>
												<ul class="dropdown-menu dropdown-sm">
													<li>
														<div class="row">
															<!-- <div class="col-md-4">
																<div class="col-inner col-disable">
																	 Heading *Need to comment out
																	<h4 class="br-green"><i class="fa fa-filter heading-icon"></i> Varsa Oukes</h4>
																	Paragraph *Need to comment out
																	<p>At vero eos et accusamus et iusto odio dignissimos ducimus qui app blanditiis praesentium voluptatum deleniti atque corrupti quos pain dolores et quas molesti as excet pturi sint occaecati cupiditate non provident.</p>
																</div>
															</div> -->
															<div class="col-md-4">
																<div class="col-inner col-disable">
																	<!-- Heading -->
																	<h4 class="br-yellow"><i class="fa fa-ticket heading-icon"></i> Episode <%= @real_eps.first.episode_number%></h4>
																	<!-- Image -->
																	<img src="/assets/w2.jpg" class="img-responsive" alt="">
																	<div class"pull-right"><%= @real_eps.first.description%> </div>
																	<!-- Paragraph -->
																	<!-- ***** Move above text right! -->
																	<!-- View Next Button -->
																	<!-- <div class="view-button">
																		<a href="#" class="btn btn-danger btn-sm">View More <i class="fa fa-angle-right"></i></a>
																	</div> -->
																</div>
															</div>
															<!-- <div class="col-md-4">
																<div class="col-inner">
																	<ul class="list-unstyled">
																		<li><a href="blog.html"><i class="fa fa-arrow-right dd-link-icon"></i> Blog</a></li>
																		<li><a href="blog-single.html"><i class="fa fa-arrow-right dd-link-icon"></i> Single Blog</a></li>
																		<li><a href="portfolio.html"><i class="fa fa-arrow-right dd-link-icon"></i> Portfolio</a></li>
																		<li><a href="pricing.html"><i class="fa fa-arrow-right dd-link-icon"></i> Pricing</a></li>
																		<li><a href="product.html"><i class="fa fa-arrow-right dd-link-icon"></i> Products</a></li>
																		<li><a href="testimonial.html"><i class="fa fa-arrow-right dd-link-icon"></i> Testimonial</a></li>
																	</ul>
																</div>
															</div> -->
														</div>
													</li>
												</ul>
											</li>
											<li>
												<a href="aboutus.html" class="br-red">
													<!-- Link Icon -->
													<i class="fa fa-user link-icon"></i>
													<!-- Link Title -->
													<span class="link-title">About</span>
												</a>
											</li>
											<li>
												<a href="#contact" class="br-yellow">
													<!-- Link Icon -->
													<i class="fa fa-phone link-icon"></i>
													<!-- Link Title -->
													<span class="link-title">Contact</span>
												</a>
											</li>
										</ul>
									</div><!-- /.navbar-collapse --> 
								</nav>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Header End -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="csstransforms csstransforms3d csstransitions" keydn="true">

  

	<head>
		<!-- Title here -->
		<title>NY Tech Podcast</title>
		<!-- Description, Keywords and Author -->
		<meta name="description" content="Your description">
		<meta name="keywords" content="Your,Keywords">
		<meta name="author" content="ResponsiveWebInc">
		
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		 <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %> 
		<!--[if IE ]><%= stylesheet_link_tag "settings-ie8", media: "all", "data-turbolinks-track" => true %><![endif]-->
		<!--[if IE ]><%= stylesheet_link_tag "ie-style", media: "all", "data-turbolinks-track" => true %><![endif]-->
		 <%= javascript_include_tag "application", "data-turbolinks-track" => true %> 

		<!-- Favicon -->
		<link rel="shortcut icon" href="#">
	<style type="text/css"></style>
	</head>
		

	<body style="">
		<div class="wrapper white">
		  
			<%= render 'layouts/header' %>
			<div class="container">
				<% flash.each do |name, msg| %>
					<%= content_tag(:div, msg, class: "alert alert-info") %>
				<% end %>
				<%= yield %>
			</div>

			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>